# Generated by Django 5.2.3 on 2025-06-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('shoes', 'Shoes'), ('accessory', 'Accessory')], max_length=20)),
                ('image', models.ImageField(upload_to='outfit_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='message',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='price',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='outfit',
            name='subject',
            field=models.CharField(default='please enter subject', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='project.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='project.profile'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(to='project.outfititem'),
        ),
    ]
