# Generated by Django 5.2.3 on 2025-06-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_outfititem_remove_image_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='OutfitImage',
        ),
        migrations.RemoveField(
            model_name='outfitimage',
            name='profile',
        ),
        migrations.AddField(
            model_name='outfitimage',
            name='outfit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.outfit'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='outfit_images/')),
                ('caption', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile')),
            ],
        ),
    ]
