# Generated by Django 5.2.3 on 2025-06-25 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0003_rename_image_outfitimage_remove_outfitimage_profile_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friend",
            name="friend",
        ),
        migrations.RemoveField(
            model_name="friend",
            name="profile",
        ),
        migrations.AddField(
            model_name="friend",
            name="profile1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile1",
                to="project.profile",
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="profile2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile2",
                to="project.profile",
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="outfit",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="outfitimage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profileimage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="outfititem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("shirt", "Shirt"),
                    ("pants", "Pants"),
                    ("shoes", "Shoes"),
                    ("accessory", "Accessory"),
                    ("dress", "Dress"),
                    ("jacket", "Jacket"),
                    ("hat", "Hat"),
                    ("bag", "Bag"),
                ],
                max_length=20,
            ),
        ),
    ]
