# Generated by Django 5.2.1 on 2025-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0003_remove_profile_image_profile_image_url_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_url",
            field=models.ImageField(blank=True, upload_to="profile_images/"),
        ),
    ]
