# Generated by Django 5.2.1 on 2025-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0004_alter_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_url",
            field=models.TextField(blank=True),
        ),
    ]
